
var blosc_codec = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(blosc_codec) {
  blosc_codec = blosc_codec || {};


var d;d||(d=typeof blosc_codec !== 'undefined' ? blosc_codec : {});var aa,ba;d.ready=new Promise(function(a,b){aa=a;ba=b});var r={},t;for(t in d)d.hasOwnProperty(t)&&(r[t]=d[t]);var ca="./this.program",da=d.print||console.log.bind(console),u=d.printErr||console.warn.bind(console);for(t in r)r.hasOwnProperty(t)&&(d[t]=r[t]);r=null;d.thisProgram&&(ca=d.thisProgram);var v;d.wasmBinary&&(v=d.wasmBinary);var noExitRuntime;d.noExitRuntime&&(noExitRuntime=d.noExitRuntime);
"object"!==typeof WebAssembly&&w("no native wasm support detected");var y,ea=new WebAssembly.Table({initial:86,maximum:86,element:"anyfunc"}),fa=!1,ha="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ia(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&ha)return ha.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}
function ja(a,b,c){var e=z;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(b>=c)break;e[b++]=g}else{if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63}e[b++]=128|g>>6&63}e[b++]=128|g&63}}e[b]=0}}var ka="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function la(a,b){var c=a>>1;for(var e=c+b/2;!(c>=e)&&A[c];)++c;c<<=1;if(32<c-a&&ka)return ka.decode(z.subarray(a,c));c=0;for(e="";;){var f=C[a+2*c>>1];if(0==f||c==b/2)return e;++c;e+=String.fromCharCode(f)}}function ma(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var e=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)C[b>>1]=a.charCodeAt(f),b+=2;C[b>>1]=0;return b-e}function na(a){return 2*a.length}
function oa(a,b){for(var c=0,e="";!(c>=b/4);){var f=D[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023)):e+=String.fromCharCode(f)}return e}function pa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}D[b>>2]=g;b+=4;if(b+4>c)break}D[b>>2]=0;return b-e}
function qa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b}var E,F,z,C,A,D,H,ra,sa;function ta(a){E=a;d.HEAP8=F=new Int8Array(a);d.HEAP16=C=new Int16Array(a);d.HEAP32=D=new Int32Array(a);d.HEAPU8=z=new Uint8Array(a);d.HEAPU16=A=new Uint16Array(a);d.HEAPU32=H=new Uint32Array(a);d.HEAPF32=ra=new Float32Array(a);d.HEAPF64=sa=new Float64Array(a)}var ua=d.INITIAL_MEMORY||16777216;d.wasmMemory?y=d.wasmMemory:y=new WebAssembly.Memory({initial:ua/65536,maximum:32768});
y&&(E=y.buffer);ua=E.byteLength;ta(E);D[8104]=5275456;function I(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.ba;"number"===typeof c?void 0===b.Y?d.dynCall_v(c):d.dynCall_vi(c,b.Y):c(void 0===b.Y?null:b.Y)}}}var va=[],wa=[],xa=[],ya=[];function za(){var a=d.preRun.shift();va.unshift(a)}var J=0,K=null,M=null;d.preloadedImages={};d.preloadedAudios={};
function w(a){if(d.onAbort)d.onAbort(a);u(a);fa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Aa(a){var b=N;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ba(){return Aa("data:application/octet-stream;base64,")}var N="blosc_codec.wasm";if(!Ba()){var Ca=N;N=d.locateFile?d.locateFile(Ca,""):""+Ca}
function Da(){return new Promise(function(a){a:{try{if(v){var b=new Uint8Array(v);break a}throw"both async and sync fetching of the wasm failed";}catch(c){w(c)}b=void 0}a(b)})}wa.push({ba:function(){Ea()}});function O(){return 0<O.$}function Fa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ga=void 0;function P(a){for(var b="";z[a];)b+=Ga[z[a++]];return b}var Q={},R={},S={};
function Ha(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ia(a,b){a=Ha(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ja(a){var b=Error,c=Ia(a,function(e){this.name=a;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ka=void 0;function T(a){throw new Ka(a);}var La=void 0;
function Ma(a,b){function c(h){h=b(h);if(h.length!==e.length)throw new La("Mismatched type converter count");for(var l=0;l<e.length;++l)U(e[l],h[l])}var e=[];e.forEach(function(h){S[h]=a});var f=Array(a.length),g=[],k=0;a.forEach(function(h,l){R.hasOwnProperty(h)?f[l]=R[h]:(g.push(h),Q.hasOwnProperty(h)||(Q[h]=[]),Q[h].push(function(){f[l]=R[h];++k;k===g.length&&c(f)}))});0===g.length&&c(f)}
function U(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||T('type "'+e+'" must have a positive integer typeid pointer');if(R.hasOwnProperty(a)){if(c.ca)return;T("Cannot register type '"+e+"' twice")}R[a]=b;delete S[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(function(f){f()}))}var Pa=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Qa(a){4<a&&0===--V[a].Z&&(V[a]=void 0,Pa.push(a))}function Ra(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Pa.length?Pa.pop():V.length;V[b]={Z:1,value:a};return b}}function Sa(a){return this.fromWireType(H[a>>2])}function Ta(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Ua(a,b){switch(b){case 2:return function(c){return this.fromWireType(ra[c>>2])};case 3:return function(c){return this.fromWireType(sa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Va(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ia(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Wa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Xa(a,b){var c=d;if(void 0===c[a].W){var e=c[a];c[a]=function(){c[a].W.hasOwnProperty(arguments.length)||T("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].W+")!");return c[a].W[arguments.length].apply(this,arguments)};c[a].W=[];c[a].W[e.aa]=e}}
function Ya(a,b,c){d.hasOwnProperty(a)?((void 0===c||void 0!==d[a].W&&void 0!==d[a].W[c])&&T("Cannot register public name '"+a+"' twice"),Xa(a,a),d.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),d[a].W[c]=b):(d[a]=b,void 0!==c&&(d[a].ea=c))}function Za(a,b){for(var c=[],e=0;e<a;e++)c.push(D[(b>>2)+e]);return c}
function $a(a,b){a=P(a);var c=d["dynCall_"+a];for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&T("unknown function pointer with signature "+a+": "+b);return c}var ab=void 0;function bb(a){a=cb(a);var b=P(a);W(a);return b}
function db(a,b){function c(g){f[g]||R[g]||(S[g]?S[g].forEach(c):(e.push(g),f[g]=!0))}var e=[],f={};b.forEach(c);throw new ab(a+": "+e.map(bb).join([", "]));}function eb(a,b,c){switch(b){case 0:return c?function(e){return F[e]}:function(e){return z[e]};case 1:return c?function(e){return C[e>>1]}:function(e){return A[e>>1]};case 2:return c?function(e){return D[e>>2]}:function(e){return H[e>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var fb={};
function gb(){if(!hb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in fb)a[b]=fb[b];var c=[];for(b in a)c.push(b+"="+a[b]);hb=c}return hb}for(var hb,ib=[null,[],[]],jb=Array(256),X=0;256>X;++X)jb[X]=String.fromCharCode(X);Ga=jb;Ka=d.BindingError=Ja("BindingError");La=d.InternalError=Ja("InternalError");
d.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};d.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};ab=d.UnboundTypeError=Ja("UnboundTypeError");
var kb={o:function(a){return Y(a)},n:function(a){"uncaught_exception"in O?O.$++:O.$=1;throw a;},y:function(a,b,c,e,f){var g=Fa(c);b=P(b);U(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?e:f},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=F;else if(2===c)h=C;else if(4===c)h=D;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[k>>g])},X:null})},x:function(a,b){b=P(b);U(a,{name:b,fromWireType:function(c){var e=V[c].value;
Qa(c);return e},toWireType:function(c,e){return Ra(e)},argPackAdvance:8,readValueFromPointer:Sa,X:null})},g:function(a,b,c){c=Fa(c);b=P(b);U(a,{name:b,fromWireType:function(e){return e},toWireType:function(e,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Ta(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Ua(b,c),X:null})},d:function(a,b,c,e,f,g){var k=Za(b,c);a=P(a);f=$a(e,f);Ya(a,function(){db("Cannot call "+a+" due to unbound types",
k)},b-1);Ma(k,function(h){var l=a,n=a;h=[h[0],null].concat(h.slice(1));var p=f,q=h.length;2>q&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var x=null!==h[1]&&!1,B=!1,m=1;m<h.length;++m)if(null!==h[m]&&void 0===h[m].X){B=!0;break}var Na="void"!==h[0].name,G="",L="";for(m=0;m<q-2;++m)G+=(0!==m?", ":"")+"arg"+m,L+=(0!==m?", ":"")+"arg"+m+"Wired";n="return function "+Ha(n)+"("+G+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+n+" called with ' + arguments.length + ' arguments, expected "+
(q-2)+" args!');\n}\n";B&&(n+="var destructors = [];\n");var Oa=B?"destructors":"null";G="throwBindingError invoker fn runDestructors retType classParam".split(" ");p=[T,p,g,Wa,h[0],h[1]];x&&(n+="var thisWired = classParam.toWireType("+Oa+", this);\n");for(m=0;m<q-2;++m)n+="var arg"+m+"Wired = argType"+m+".toWireType("+Oa+", arg"+m+"); // "+h[m+2].name+"\n",G.push("argType"+m),p.push(h[m+2]);x&&(L="thisWired"+(0<L.length?", ":"")+L);n+=(Na?"var rv = ":"")+"invoker(fn"+(0<L.length?", ":"")+L+");\n";
if(B)n+="runDestructors(destructors);\n";else for(m=x?1:2;m<h.length;++m)q=1===m?"thisWired":"arg"+(m-2)+"Wired",null!==h[m].X&&(n+=q+"_dtor("+q+"); // "+h[m].name+"\n",G.push(q+"_dtor"),p.push(h[m].X));Na&&(n+="var ret = retType.fromWireType(rv);\nreturn ret;\n");G.push(n+"}\n");h=Va(G).apply(null,p);m=b-1;if(!d.hasOwnProperty(l))throw new La("Replacing nonexistant public symbol");void 0!==d[l].W&&void 0!==m?d[l].W[m]=h:(d[l]=h,d[l].aa=m);return[]})},b:function(a,b,c,e,f){function g(n){return n}
b=P(b);-1===f&&(f=4294967295);var k=Fa(c);if(0===e){var h=32-8*c;g=function(n){return n<<h>>>h}}var l=-1!=b.indexOf("unsigned");U(a,{name:b,fromWireType:g,toWireType:function(n,p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+Ta(p)+'" to '+this.name);if(p<e||p>f)throw new TypeError('Passing a number "'+Ta(p)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return l?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:eb(b,
k,0!==e),X:null})},a:function(a,b,c){function e(g){g>>=2;var k=H;return new f(E,k[g+1],k[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);U(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{ca:!0})},h:function(a,b){b=P(b);var c="std::string"===b;U(a,{name:b,fromWireType:function(e){var f=H[e>>2];if(c)for(var g=e+4,k=0;k<=f;++k){var h=e+4+k;if(k==f||0==z[h]){g=g?ia(z,g,h-g):"";if(void 0===l)var l=g;else l+=String.fromCharCode(0),
l+=g;g=h+1}}else{l=Array(f);for(k=0;k<f;++k)l[k]=String.fromCharCode(z[e+4+k]);l=l.join("")}W(e);return l},toWireType:function(e,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||T("Cannot pass non-string to std::string");var k=(c&&g?function(){for(var n=0,p=0;p<f.length;++p){var q=f.charCodeAt(p);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|f.charCodeAt(++p)&1023);127>=q?++n:n=2047>=q?n+
2:65535>=q?n+3:n+4}return n}:function(){return f.length})(),h=Y(4+k+1);H[h>>2]=k;if(c&&g)ja(f,h+4,k+1);else if(g)for(g=0;g<k;++g){var l=f.charCodeAt(g);255<l&&(W(h),T("String has UTF-16 code units that do not fit in 8 bits"));z[h+4+g]=l}else for(g=0;g<k;++g)z[h+4+g]=f[g];null!==e&&e.push(W,h);return h},argPackAdvance:8,readValueFromPointer:Sa,X:function(e){W(e)}})},c:function(a,b,c){c=P(c);if(2===b){var e=la;var f=ma;var g=na;var k=function(){return A};var h=1}else 4===b&&(e=oa,f=pa,g=qa,k=function(){return H},
h=2);U(a,{name:c,fromWireType:function(l){for(var n=H[l>>2],p=k(),q,x=l+4,B=0;B<=n;++B){var m=l+4+B*b;if(B==n||0==p[m>>h])x=e(x,m-x),void 0===q?q=x:(q+=String.fromCharCode(0),q+=x),x=m+b}W(l);return q},toWireType:function(l,n){"string"!==typeof n&&T("Cannot pass non-string to C++ string type "+c);var p=g(n),q=Y(4+p+b);H[q>>2]=p>>h;f(n,q+4,p+b);null!==l&&l.push(W,q);return q},argPackAdvance:8,readValueFromPointer:Sa,X:function(l){W(l)}})},z:function(a,b){b=P(b);U(a,{da:!0,name:b,argPackAdvance:0,fromWireType:function(){},
toWireType:function(){}})},m:Qa,w:function(a){4<a&&(V[a].Z+=1)},B:function(a,b){var c=R[a];void 0===c&&T("_emval_take_value has unknown type "+bb(a));a=c.readValueFromPointer(b);return Ra(a)},s:function(){w()},q:function(a,b,c){z.copyWithin(a,b,b+c)},r:function(a){a>>>=0;var b=z.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(16777216,a,e);0<e%65536&&(e+=65536-e%65536);a:{try{y.grow(Math.min(2147483648,e)-E.byteLength+65535>>>16);ta(y.buffer);
var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},t:function(a,b){var c=0;gb().forEach(function(e,f){var g=b+c;f=D[a+4*f>>2]=g;for(g=0;g<e.length;++g)F[f++>>0]=e.charCodeAt(g);F[f>>0]=0;c+=e.length+1});return 0},u:function(a,b){var c=gb();D[a>>2]=c.length;var e=0;c.forEach(function(f){e+=f.length+1});D[b>>2]=e;return 0},v:function(){return 0},p:function(){},f:function(a,b,c,e){for(var f=0,g=0;g<c;g++){for(var k=D[b+8*g>>2],h=D[b+(8*g+4)>>2],l=0;l<h;l++){var n=z[k+l],p=ib[a];0===n||10===n?
((1===a?da:u)(ia(p,0)),p.length=0):p.push(n)}f+=h}D[e>>2]=f;return 0},memory:y,k:function(){return 0},j:function(){return 0},i:function(){},A:function(){return 6},l:function(){},e:function(){},table:ea};
(function(){function a(f){d.asm=f.exports;J--;d.monitorRunDependencies&&d.monitorRunDependencies(J);0==J&&(null!==K&&(clearInterval(K),K=null),M&&(f=M,M=null,f()))}function b(f){a(f.instance)}function c(f){return Da().then(function(g){return WebAssembly.instantiate(g,e)}).then(f,function(g){u("failed to asynchronously prepare wasm: "+g);w(g)})}var e={a:kb};J++;d.monitorRunDependencies&&d.monitorRunDependencies(J);if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return u("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(v||"function"!==typeof WebAssembly.instantiateStreaming||Ba()||Aa("file://")||"function"!==typeof fetch)return c(b);fetch(N,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){u("wasm streaming compile failed: "+g);u("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Ea=d.___wasm_call_ctors=function(){return(Ea=d.___wasm_call_ctors=d.asm.C).apply(null,arguments)},Y=d._malloc=function(){return(Y=d._malloc=d.asm.D).apply(null,arguments)},W=d._free=function(){return(W=d._free=d.asm.E).apply(null,arguments)},cb=d.___getTypeName=function(){return(cb=d.___getTypeName=d.asm.F).apply(null,arguments)};d.___embind_register_native_and_builtin_types=function(){return(d.___embind_register_native_and_builtin_types=d.asm.G).apply(null,arguments)};
d.dynCall_ii=function(){return(d.dynCall_ii=d.asm.H).apply(null,arguments)};d.dynCall_vi=function(){return(d.dynCall_vi=d.asm.I).apply(null,arguments)};d.dynCall_iii=function(){return(d.dynCall_iii=d.asm.J).apply(null,arguments)};d.dynCall_vii=function(){return(d.dynCall_vii=d.asm.K).apply(null,arguments)};d.dynCall_viii=function(){return(d.dynCall_viii=d.asm.L).apply(null,arguments)};d.dynCall_iiii=function(){return(d.dynCall_iiii=d.asm.M).apply(null,arguments)};
d.dynCall_iiiiiii=function(){return(d.dynCall_iiiiiii=d.asm.N).apply(null,arguments)};d.dynCall_viiiiii=function(){return(d.dynCall_viiiiii=d.asm.O).apply(null,arguments)};d.dynCall_v=function(){return(d.dynCall_v=d.asm.P).apply(null,arguments)};d.dynCall_iiiii=function(){return(d.dynCall_iiiii=d.asm.Q).apply(null,arguments)};d.dynCall_jiiiii=function(){return(d.dynCall_jiiiii=d.asm.R).apply(null,arguments)};d.dynCall_viiii=function(){return(d.dynCall_viiii=d.asm.S).apply(null,arguments)};
d.dynCall_iiiiii=function(){return(d.dynCall_iiiiii=d.asm.T).apply(null,arguments)};d.dynCall_jiji=function(){return(d.dynCall_jiji=d.asm.U).apply(null,arguments)};d.dynCall_viiiii=function(){return(d.dynCall_viiiii=d.asm.V).apply(null,arguments)};var Z;M=function lb(){Z||mb();Z||(M=lb)};
function mb(){function a(){if(!Z&&(Z=!0,d.calledRun=!0,!fa)){I(wa);I(xa);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();ya.unshift(b)}I(ya)}}if(!(0<J)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)za();I(va);0<J||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}
d.run=mb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();noExitRuntime=!0;mb();


  return blosc_codec.ready
}
);
})();
export default blosc_codec;