
var lz4_codec = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(lz4_codec) {
  lz4_codec = lz4_codec || {};


var d;d||(d=typeof lz4_codec !== 'undefined' ? lz4_codec : {});var aa,ba;d.ready=new Promise(function(a,b){aa=a;ba=b});var t={},u;for(u in d)d.hasOwnProperty(u)&&(t[u]=d[u]);var v=d.printErr||console.warn.bind(console);for(u in t)t.hasOwnProperty(u)&&(d[u]=t[u]);t=null;var x;d.wasmBinary&&(x=d.wasmBinary);var noExitRuntime;d.noExitRuntime&&(noExitRuntime=d.noExitRuntime);"object"!==typeof WebAssembly&&y("no native wasm support detected");
var z,ca=new WebAssembly.Table({initial:32,maximum:32,element:"anyfunc"}),da=!1,ea="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function fa(a,b,c){var e=A;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(b>=c)break;e[b++]=g}else{if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63}e[b++]=128|g>>6&63}e[b++]=128|g&63}}e[b]=0}}var ha="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function ia(a,b){var c=a>>1;for(var e=c+b/2;!(c>=e)&&B[c];)++c;c<<=1;if(32<c-a&&ha)return ha.decode(A.subarray(a,c));c=0;for(e="";;){var f=C[a+2*c>>1];if(0==f||c==b/2)return e;++c;e+=String.fromCharCode(f)}}function ja(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var e=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)C[b>>1]=a.charCodeAt(f),b+=2;C[b>>1]=0;return b-e}function ka(a){return 2*a.length}
function la(a,b){for(var c=0,e="";!(c>=b/4);){var f=D[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023)):e+=String.fromCharCode(f)}return e}function ma(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var n=a.charCodeAt(++f);g=65536+((g&1023)<<10)|n&1023}D[b>>2]=g;b+=4;if(b+4>c)break}D[b>>2]=0;return b-e}
function na(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b}var E,F,A,C,B,D,H,oa,pa;function qa(a){E=a;d.HEAP8=F=new Int8Array(a);d.HEAP16=C=new Int16Array(a);d.HEAP32=D=new Int32Array(a);d.HEAPU8=A=new Uint8Array(a);d.HEAPU16=B=new Uint16Array(a);d.HEAPU32=H=new Uint32Array(a);d.HEAPF32=oa=new Float32Array(a);d.HEAPF64=pa=new Float64Array(a)}var ra=d.INITIAL_MEMORY||16777216;d.wasmMemory?z=d.wasmMemory:z=new WebAssembly.Memory({initial:ra/65536,maximum:32768});
z&&(E=z.buffer);ra=E.byteLength;qa(E);D[1188]=5247792;function I(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.N;"number"===typeof c?void 0===b.J?d.dynCall_v(c):d.dynCall_vi(c,b.J):c(void 0===b.J?null:b.J)}}}var sa=[],ta=[],ua=[],va=[];function wa(){var a=d.preRun.shift();sa.unshift(a)}var J=0,L=null,M=null;d.preloadedImages={};d.preloadedAudios={};
function y(a){if(d.onAbort)d.onAbort(a);v(a);da=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function xa(a){var b=N;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function ya(){return xa("data:application/octet-stream;base64,")}var N="lz4_codec.wasm";if(!ya()){var za=N;N=d.locateFile?d.locateFile(za,""):""+za}
function Aa(){try{if(x)return new Uint8Array(x);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}ta.push({N:function(){Ba()}});function Ca(a){this.I=a-16;this.V=function(b){D[this.I+8>>2]=b};this.S=function(b){D[this.I+0>>2]=b};this.T=function(){D[this.I+4>>2]=0};this.R=function(){F[this.I+12>>0]=0};this.U=function(){F[this.I+13>>0]=0};this.P=function(b,c){this.V(b);this.S(c);this.T();this.R();this.U()}}function O(){return 0<O.L}
function Da(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ea=void 0;function P(a){for(var b="";A[a];)b+=Ea[A[a++]];return b}var Q={},R={},S={};function Fa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Ga(a,b){a=Fa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Ha(a){var b=Error,c=Ga(a,function(e){this.name=a;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Ka=void 0;function T(a){throw new Ka(a);}var La=void 0;function Ma(a,b){function c(h){h=b(h);if(h.length!==e.length)throw new La("Mismatched type converter count");for(var l=0;l<e.length;++l)U(e[l],h[l])}var e=[];e.forEach(function(h){S[h]=a});var f=Array(a.length),g=[],n=0;a.forEach(function(h,l){R.hasOwnProperty(h)?f[l]=R[h]:(g.push(h),Q.hasOwnProperty(h)||(Q[h]=[]),Q[h].push(function(){f[l]=R[h];++n;n===g.length&&c(f)}))});0===g.length&&c(f)}
function U(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||T('type "'+e+'" must have a positive integer typeid pointer');if(R.hasOwnProperty(a)){if(c.O)return;T("Cannot register type '"+e+"' twice")}R[a]=b;delete S[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(function(f){f()}))}var Na=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Oa(a){4<a&&0===--V[a].K&&(V[a]=void 0,Na.push(a))}function Pa(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Na.length?Na.pop():V.length;V[b]={K:1,value:a};return b}}function Qa(a){return this.fromWireType(H[a>>2])}function Ra(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Sa(a,b){switch(b){case 2:return function(c){return this.fromWireType(oa[c>>2])};case 3:return function(c){return this.fromWireType(pa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Ta(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ga(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Ua(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Va(a,b){var c=d;if(void 0===c[a].G){var e=c[a];c[a]=function(){c[a].G.hasOwnProperty(arguments.length)||T("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].G+")!");return c[a].G[arguments.length].apply(this,arguments)};c[a].G=[];c[a].G[e.M]=e}}
function Wa(a,b,c){d.hasOwnProperty(a)?((void 0===c||void 0!==d[a].G&&void 0!==d[a].G[c])&&T("Cannot register public name '"+a+"' twice"),Va(a,a),d.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),d[a].G[c]=b):(d[a]=b,void 0!==c&&(d[a].X=c))}function Xa(a,b){for(var c=[],e=0;e<a;e++)c.push(D[(b>>2)+e]);return c}
function Ya(a,b){a=P(a);var c=d["dynCall_"+a];for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&T("unknown function pointer with signature "+a+": "+b);return c}var Za=void 0;function $a(a){a=ab(a);var b=P(a);W(a);return b}
function bb(a,b){function c(g){f[g]||R[g]||(S[g]?S[g].forEach(c):(e.push(g),f[g]=!0))}var e=[],f={};b.forEach(c);throw new Za(a+": "+e.map($a).join([", "]));}function cb(a,b,c){switch(b){case 0:return c?function(e){return F[e]}:function(e){return A[e]};case 1:return c?function(e){return C[e>>1]}:function(e){return B[e>>1]};case 2:return c?function(e){return D[e>>2]}:function(e){return H[e>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var db=Array(256),X=0;256>X;++X)db[X]=String.fromCharCode(X);
Ea=db;Ka=d.BindingError=Ha("BindingError");La=d.InternalError=Ha("InternalError");d.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};d.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};Za=d.UnboundTypeError=Ha("UnboundTypeError");
var eb={k:function(a){return Y(a+16)+16},j:function(a,b,c){(new Ca(a)).P(b,c);"uncaught_exception"in O?O.L++:O.L=1;throw a;},g:function(a,b,c,e,f){var g=Da(c);b=P(b);U(a,{name:b,fromWireType:function(n){return!!n},toWireType:function(n,h){return h?e:f},argPackAdvance:8,readValueFromPointer:function(n){if(1===c)var h=F;else if(2===c)h=C;else if(4===c)h=D;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[n>>g])},H:null})},p:function(a,b){b=P(b);U(a,{name:b,fromWireType:function(c){var e=
V[c].value;Oa(c);return e},toWireType:function(c,e){return Pa(e)},argPackAdvance:8,readValueFromPointer:Qa,H:null})},f:function(a,b,c){c=Da(c);b=P(b);U(a,{name:b,fromWireType:function(e){return e},toWireType:function(e,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Ra(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Sa(b,c),H:null})},d:function(a,b,c,e,f,g){var n=Xa(b,c);a=P(a);f=Ya(e,f);Wa(a,function(){bb("Cannot call "+a+" due to unbound types",
n)},b-1);Ma(n,function(h){var l=a,p=a;h=[h[0],null].concat(h.slice(1));var q=f,m=h.length;2>m&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var r=null!==h[1]&&!1,w=!1,k=1;k<h.length;++k)if(null!==h[k]&&void 0===h[k].H){w=!0;break}var Ia="void"!==h[0].name,G="",K="";for(k=0;k<m-2;++k)G+=(0!==k?", ":"")+"arg"+k,K+=(0!==k?", ":"")+"arg"+k+"Wired";p="return function "+Fa(p)+"("+G+") {\nif (arguments.length !== "+(m-2)+") {\nthrowBindingError('function "+p+" called with ' + arguments.length + ' arguments, expected "+
(m-2)+" args!');\n}\n";w&&(p+="var destructors = [];\n");var Ja=w?"destructors":"null";G="throwBindingError invoker fn runDestructors retType classParam".split(" ");q=[T,q,g,Ua,h[0],h[1]];r&&(p+="var thisWired = classParam.toWireType("+Ja+", this);\n");for(k=0;k<m-2;++k)p+="var arg"+k+"Wired = argType"+k+".toWireType("+Ja+", arg"+k+"); // "+h[k+2].name+"\n",G.push("argType"+k),q.push(h[k+2]);r&&(K="thisWired"+(0<K.length?", ":"")+K);p+=(Ia?"var rv = ":"")+"invoker(fn"+(0<K.length?", ":"")+K+");\n";
if(w)p+="runDestructors(destructors);\n";else for(k=r?1:2;k<h.length;++k)m=1===k?"thisWired":"arg"+(k-2)+"Wired",null!==h[k].H&&(p+=m+"_dtor("+m+"); // "+h[k].name+"\n",G.push(m+"_dtor"),q.push(h[k].H));Ia&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");G.push(p+"}\n");h=Ta(G).apply(null,q);k=b-1;if(!d.hasOwnProperty(l))throw new La("Replacing nonexistant public symbol");void 0!==d[l].G&&void 0!==k?d[l].G[k]=h:(d[l]=h,d[l].M=k);return[]})},b:function(a,b,c,e,f){function g(p){return p}b=
P(b);-1===f&&(f=4294967295);var n=Da(c);if(0===e){var h=32-8*c;g=function(p){return p<<h>>>h}}var l=-1!=b.indexOf("unsigned");U(a,{name:b,fromWireType:g,toWireType:function(p,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+Ra(q)+'" to '+this.name);if(q<e||q>f)throw new TypeError('Passing a number "'+Ra(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return l?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:cb(b,
n,0!==e),H:null})},a:function(a,b,c){function e(g){g>>=2;var n=H;return new f(E,n[g+1],n[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);U(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{O:!0})},e:function(a,b){b=P(b);var c="std::string"===b;U(a,{name:b,fromWireType:function(e){var f=H[e>>2];if(c)for(var g=e+4,n=0;n<=f;++n){var h=e+4+n;if(n==f||0==A[h]){if(g){var l=g;var p=A,q=l+(h-g);for(g=l;p[g]&&!(g>=q);)++g;
if(16<g-l&&p.subarray&&ea)l=ea.decode(p.subarray(l,g));else{for(q="";l<g;){var m=p[l++];if(m&128){var r=p[l++]&63;if(192==(m&224))q+=String.fromCharCode((m&31)<<6|r);else{var w=p[l++]&63;m=224==(m&240)?(m&15)<<12|r<<6|w:(m&7)<<18|r<<12|w<<6|p[l++]&63;65536>m?q+=String.fromCharCode(m):(m-=65536,q+=String.fromCharCode(55296|m>>10,56320|m&1023))}}else q+=String.fromCharCode(m)}l=q}}else l="";if(void 0===k)var k=l;else k+=String.fromCharCode(0),k+=l;g=h+1}}else{k=Array(f);for(n=0;n<f;++n)k[n]=String.fromCharCode(A[e+
4+n]);k=k.join("")}W(e);return k},toWireType:function(e,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||T("Cannot pass non-string to std::string");var n=(c&&g?function(){for(var p=0,q=0;q<f.length;++q){var m=f.charCodeAt(q);55296<=m&&57343>=m&&(m=65536+((m&1023)<<10)|f.charCodeAt(++q)&1023);127>=m?++p:p=2047>=m?p+2:65535>=m?p+3:p+4}return p}:function(){return f.length})(),h=Y(4+n+1);H[h>>
2]=n;if(c&&g)fa(f,h+4,n+1);else if(g)for(g=0;g<n;++g){var l=f.charCodeAt(g);255<l&&(W(h),T("String has UTF-16 code units that do not fit in 8 bits"));A[h+4+g]=l}else for(g=0;g<n;++g)A[h+4+g]=f[g];null!==e&&e.push(W,h);return h},argPackAdvance:8,readValueFromPointer:Qa,H:function(e){W(e)}})},c:function(a,b,c){c=P(c);if(2===b){var e=ia;var f=ja;var g=ka;var n=function(){return B};var h=1}else 4===b&&(e=la,f=ma,g=na,n=function(){return H},h=2);U(a,{name:c,fromWireType:function(l){for(var p=H[l>>2],q=
n(),m,r=l+4,w=0;w<=p;++w){var k=l+4+w*b;if(w==p||0==q[k>>h])r=e(r,k-r),void 0===m?m=r:(m+=String.fromCharCode(0),m+=r),r=k+b}W(l);return m},toWireType:function(l,p){"string"!==typeof p&&T("Cannot pass non-string to C++ string type "+c);var q=g(p),m=Y(4+q+b);H[m>>2]=q>>h;f(p,m+4,q+b);null!==l&&l.push(W,m);return m},argPackAdvance:8,readValueFromPointer:Qa,H:function(l){W(l)}})},h:function(a,b){b=P(b);U(a,{W:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},i:Oa,l:function(a){4<
a&&(V[a].K+=1)},q:function(a,b){var c=R[a];void 0===c&&T("_emval_take_value has unknown type "+$a(a));a=c.readValueFromPointer(b);return Pa(a)},o:function(){y()},m:function(a,b,c){A.copyWithin(a,b,b+c)},n:function(a){a>>>=0;var b=A.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(16777216,a,e);0<e%65536&&(e+=65536-e%65536);a:{try{z.grow(Math.min(2147483648,e)-E.byteLength+65535>>>16);qa(z.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},
memory:z,table:ca};
(function(){function a(f){d.asm=f.exports;J--;d.monitorRunDependencies&&d.monitorRunDependencies(J);0==J&&(null!==L&&(clearInterval(L),L=null),M&&(f=M,M=null,f()))}function b(f){a(f.instance)}function c(f){return Promise.resolve().then(Aa).then(function(g){return WebAssembly.instantiate(g,e)}).then(f,function(g){v("failed to asynchronously prepare wasm: "+g);y(g)})}var e={a:eb};J++;d.monitorRunDependencies&&d.monitorRunDependencies(J);if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return v("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(x||"function"!==typeof WebAssembly.instantiateStreaming||ya()||xa("file://")||"function"!==typeof fetch)return c(b);fetch(N,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){v("wasm streaming compile failed: "+g);v("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Ba=d.___wasm_call_ctors=function(){return(Ba=d.___wasm_call_ctors=d.asm.r).apply(null,arguments)},Y=d._malloc=function(){return(Y=d._malloc=d.asm.s).apply(null,arguments)},W=d._free=function(){return(W=d._free=d.asm.t).apply(null,arguments)},ab=d.___getTypeName=function(){return(ab=d.___getTypeName=d.asm.u).apply(null,arguments)};d.___embind_register_native_and_builtin_types=function(){return(d.___embind_register_native_and_builtin_types=d.asm.v).apply(null,arguments)};
d.dynCall_iii=function(){return(d.dynCall_iii=d.asm.w).apply(null,arguments)};d.dynCall_vii=function(){return(d.dynCall_vii=d.asm.x).apply(null,arguments)};d.dynCall_iiii=function(){return(d.dynCall_iiii=d.asm.y).apply(null,arguments)};d.dynCall_viii=function(){return(d.dynCall_viii=d.asm.z).apply(null,arguments)};d.dynCall_vi=function(){return(d.dynCall_vi=d.asm.A).apply(null,arguments)};d.dynCall_v=function(){return(d.dynCall_v=d.asm.B).apply(null,arguments)};
d.dynCall_ii=function(){return(d.dynCall_ii=d.asm.C).apply(null,arguments)};d.dynCall_viiiiii=function(){return(d.dynCall_viiiiii=d.asm.D).apply(null,arguments)};d.dynCall_viiiii=function(){return(d.dynCall_viiiii=d.asm.E).apply(null,arguments)};d.dynCall_viiii=function(){return(d.dynCall_viiii=d.asm.F).apply(null,arguments)};var Z;M=function fb(){Z||gb();Z||(M=fb)};
function gb(){function a(){if(!Z&&(Z=!0,d.calledRun=!0,!da)){I(ta);I(ua);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();va.unshift(b)}I(va)}}if(!(0<J)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)wa();I(sa);0<J||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}
d.run=gb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();noExitRuntime=!0;gb();


  return lz4_codec.ready
}
);
})();
export default lz4_codec;