
var zstd_codec = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,r,ba=new Promise((a,b)=>{aa=a;r=b}),ca=Object.assign({},f),t=f.printErr||console.error.bind(console);Object.assign(f,ca);ca=null;var w;f.wasmBinary&&(w=f.wasmBinary);var z,ea=!1,A,B,C,D,F,G,fa,ha;function ia(){var a=z.buffer;f.HEAP8=A=new Int8Array(a);f.HEAP16=C=new Int16Array(a);f.HEAPU8=B=new Uint8Array(a);f.HEAPU16=D=new Uint16Array(a);f.HEAP32=F=new Int32Array(a);f.HEAPU32=G=new Uint32Array(a);f.HEAPF32=fa=new Float32Array(a);f.HEAPF64=ha=new Float64Array(a)}
var ja=[],ka=[],la=[],ma=!1;function na(){var a=f.preRun.shift();ja.unshift(a)}var H=0,J=null,K=null;function oa(a){f.onAbort?.(a);a="Aborted("+a+")";t(a);ea=!0;a+=". Build with -sASSERTIONS for more info.";ma&&pa();a=new WebAssembly.RuntimeError(a);r(a);throw a;}var qa=a=>a.startsWith("data:application/octet-stream;base64,"),ra=a=>a.startsWith("file://"),L;function sa(a){if(a==L&&w)return new Uint8Array(w);throw"both async and sync fetching of the wasm failed";}
function ta(a){return w?Promise.resolve().then(()=>sa(a)):(void 0)(a).then(b=>new Uint8Array(b),()=>sa(a))}function ua(a,b,c){return ta(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{t(`failed to asynchronously prepare wasm: ${d}`);oa(d)})}
function va(a,b){var c=L;return w||"function"!=typeof WebAssembly.instantiateStreaming||qa(c)||ra(c)||"function"!=typeof fetch?ua(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){t(`wasm streaming compile failed: ${e}`);t("falling back to ArrayBuffer instantiation");return ua(c,a,b)}))}
var M=a=>{for(;0<a.length;)a.shift()(f)},wa,N=a=>{for(var b="";B[a];)b+=wa[B[a++]];return b},O={},P={},Q={},R,xa=a=>{throw new R(a);},S,ya=(a,b)=>{function c(h){h=b(h);if(h.length!==d.length)throw new S("Mismatched type converter count");for(var g=0;g<d.length;++g)T(d[g],h[g])}var d=[];d.forEach(function(h){Q[h]=a});var e=Array(a.length),k=[],l=0;a.forEach((h,g)=>{P.hasOwnProperty(h)?e[g]=P[h]:(k.push(h),O.hasOwnProperty(h)||(O[h]=[]),O[h].push(()=>{e[g]=P[h];++l;l===k.length&&c(e)}))});0===k.length&&
c(e)};function za(a,b,c={}){var d=b.name;if(!a)throw new R(`type "${d}" must have a positive integer typeid pointer`);if(P.hasOwnProperty(a)){if(c.C)return;throw new R(`Cannot register type '${d}' twice`);}P[a]=b;delete Q[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(e=>e()))}function T(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return za(a,b,c)}
var U=[],V=[],Aa=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=U.pop()||V.length;V[b]=a;V[b+1]=1;return b}};function Ba(a){return this.fromWireType(G[a>>2])}
var Ca={name:"emscripten::val",fromWireType:a=>{if(!a)throw new R("Cannot use deleted val. handle = "+a);var b=V[a];9<a&&0===--V[a+1]&&(V[a]=void 0,U.push(a));return b},toWireType:(a,b)=>Aa(b),argPackAdvance:8,readValueFromPointer:Ba,A:null},Da=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(fa[c>>2])};case 8:return function(c){return this.fromWireType(ha[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ga=(a,b)=>Object.defineProperty(b,"name",{value:a}),
Ha=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Ia(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].A)return!0;return!1}function Ja(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Ga(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
for(var Ka=(a,b)=>{if(void 0===f[a].v){var c=f[a];f[a]=function(...d){if(!f[a].v.hasOwnProperty(d.length))throw new R(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${f[a].v})!`);return f[a].v[d.length].apply(this,d)};f[a].v=[];f[a].v[c.B]=c}},La=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].v&&void 0!==f[a].v[c])throw new R(`Cannot register public name '${a}' twice`);Ka(a,a);if(f.hasOwnProperty(c))throw new R(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].v[c]=b}else f[a]=b,void 0!==c&&(f[a].F=c)},Ma=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(G[b+4*d>>2]);return c},Na,Oa=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,f["dynCall_"+a])(b,...c)):b=Na.get(b)(...c);return b},Pa=(a,b)=>(...c)=>Oa(a,b,c),Qa=(a,b)=>{a=N(a);var c=a.includes("j")?Pa(a,b):Na.get(b);if("function"!=typeof c)throw new R(`unknown function pointer with signature ${a}: ${b}`);return c},Ra,Ta=a=>{a=Sa(a);var b=N(a);W(a);return b},Ua=(a,b)=>{function c(k){e[k]||P[k]||(Q[k]?
Q[k].forEach(c):(d.push(k),e[k]=!0))}var d=[],e={};b.forEach(c);throw new Ra(`${a}: `+d.map(Ta).join([", "]));},Va=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Wa=(a,b,c)=>{switch(b){case 1:return c?d=>A[d]:d=>B[d];case 2:return c?d=>C[d>>1]:d=>D[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Xa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Ya="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):
void 0,Za=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&D[c];)++c;c<<=1;if(32<c-a&&Ya)return Ya.decode(B.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=C[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},$a=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)C[b>>1]=a.charCodeAt(e),b+=2;C[b>>1]=0;return b-d},ab=a=>2*a.length,bb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=F[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},cb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var k=a.charCodeAt(e);if(55296<=k&&57343>=k){var l=a.charCodeAt(++e);k=65536+((k&1023)<<10)|l&1023}F[b>>2]=k;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d},db=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},eb=Array(256),X=0;256>X;++X)eb[X]=String.fromCharCode(X);wa=eb;
R=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};S=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};V.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>V.length/2-5-U.length;
Ra=f.UnboundTypeError=((a,b)=>{var c=Ga(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var gb={l:()=>{oa("")},k:()=>{},i:(a,b,c,d)=>{b=N(b);T(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,k){return k?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(B[e])},A:null})},h:a=>T(a,Ca),e:(a,b,c)=>{b=N(b);T(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Da(b,c),A:null})},d:(a,b,c,d,e,k,l)=>{var h=Ma(b,c);a=N(a);a=Va(a);e=Qa(d,e);La(a,function(){Ua(`Cannot call ${a} due to unbound types`,h)},b-1);ya(h,
g=>{var p=a;var m=a;g=[g[0],null].concat(g.slice(1));var q=e,n=g.length;if(2>n)throw new R("argTypes array size mismatch! Must at least get return value and 'this' types!");var v=null!==g[1]&&!1,E=Ia(g),x="void"!==g[0].name;q=[m,xa,q,k,Ha,g[0],g[1]];for(var u=0;u<n-2;++u)q.push(g[u+2]);if(!E)for(u=v?1:2;u<g.length;++u)null!==g[u].A&&q.push(g[u].A);E=Ia(g);u=g.length;var y="",I="";for(n=0;n<u-2;++n)y+=(0!==n?", ":"")+"arg"+n,I+=(0!==n?", ":"")+"arg"+n+"Wired";y=`\n        return function (${y}) {\n        if (arguments.length !== ${u-
2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${u-2}');\n        }`;E&&(y+="var destructors = [];\n");var Ea=E?"destructors":"null",da="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");v&&(y+="var thisWired = classParam['toWireType']("+Ea+", this);\n");for(n=0;n<u-2;++n)y+="var arg"+n+"Wired = argType"+n+"['toWireType']("+Ea+", arg"+n+");\n",da.push("argType"+n);v&&(I="thisWired"+(0<I.length?
", ":"")+I);y+=(x||l?"var rv = ":"")+"invoker(fn"+(0<I.length?", ":"")+I+");\n";if(E)y+="runDestructors(destructors);\n";else for(n=v?1:2;n<g.length;++n)v=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==g[n].A&&(y+=`${v}_dtor(${v});\n`,da.push(`${v}_dtor`));x&&(y+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [Fa,hb]=[da,y+"}\n"];Fa.push(hb);g=Ja(Fa)(...q);m=Ga(m,g);g=b-1;if(!f.hasOwnProperty(p))throw new S("Replacing nonexistent public symbol");void 0!==f[p].v&&void 0!==g?f[p].v[g]=m:
(f[p]=m,f[p].B=g);return[]})},b:(a,b,c,d,e)=>{b=N(b);-1===e&&(e=4294967295);e=h=>h;if(0===d){var k=32-8*c;e=h=>h<<k>>>k}var l=b.includes("unsigned")?function(h,g){return g>>>0}:function(h,g){return g};T(a,{name:b,fromWireType:e,toWireType:l,argPackAdvance:8,readValueFromPointer:Wa(b,c,0!==d),A:null})},a:(a,b,c)=>{function d(k){return new e(A.buffer,G[k+4>>2],G[k>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=N(c);T(a,{name:c,fromWireType:d,
argPackAdvance:8,readValueFromPointer:d},{C:!0})},f:(a,b)=>{b=N(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var e=G[d>>2],k=d+4;if(c)for(var l=k,h=0;h<=e;++h){var g=k+h;if(h==e||0==B[g]){if(l){var p=l;var m=B,q=p+(g-l);for(l=p;m[l]&&!(l>=q);)++l;if(16<l-p&&m.buffer&&Xa)p=Xa.decode(m.subarray(p,l));else{for(q="";p<l;){var n=m[p++];if(n&128){var v=m[p++]&63;if(192==(n&224))q+=String.fromCharCode((n&31)<<6|v);else{var E=m[p++]&63;n=224==(n&240)?(n&15)<<12|v<<6|E:(n&7)<<18|v<<12|E<<
6|m[p++]&63;65536>n?q+=String.fromCharCode(n):(n-=65536,q+=String.fromCharCode(55296|n>>10,56320|n&1023))}}else q+=String.fromCharCode(n)}p=q}}else p="";if(void 0===x)var x=p;else x+=String.fromCharCode(0),x+=p;l=g+1}}else{x=Array(e);for(h=0;h<e;++h)x[h]=String.fromCharCode(B[k+h]);x=x.join("")}W(d);return x},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var k,l="string"==typeof e;if(!(l||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new R("Cannot pass non-string to std::string");
var h;if(c&&l)for(k=h=0;k<e.length;++k){var g=e.charCodeAt(k);127>=g?h++:2047>=g?h+=2:55296<=g&&57343>=g?(h+=4,++k):h+=3}else h=e.length;k=h;h=fb(4+k+1);g=h+4;G[h>>2]=k;if(c&&l){if(l=g,g=k+1,k=B,0<g){g=l+g-1;for(var p=0;p<e.length;++p){var m=e.charCodeAt(p);if(55296<=m&&57343>=m){var q=e.charCodeAt(++p);m=65536+((m&1023)<<10)|q&1023}if(127>=m){if(l>=g)break;k[l++]=m}else{if(2047>=m){if(l+1>=g)break;k[l++]=192|m>>6}else{if(65535>=m){if(l+2>=g)break;k[l++]=224|m>>12}else{if(l+3>=g)break;k[l++]=240|
m>>18;k[l++]=128|m>>12&63}k[l++]=128|m>>6&63}k[l++]=128|m&63}}k[l]=0}}else if(l)for(l=0;l<k;++l){p=e.charCodeAt(l);if(255<p)throw W(g),new R("String has UTF-16 code units that do not fit in 8 bits");B[g+l]=p}else for(l=0;l<k;++l)B[g+l]=e[l];null!==d&&d.push(W,h);return h},argPackAdvance:8,readValueFromPointer:Ba,A(d){W(d)}})},c:(a,b,c)=>{c=N(c);if(2===b){var d=Za;var e=$a;var k=ab;var l=h=>D[h>>1]}else 4===b&&(d=bb,e=cb,k=db,l=h=>G[h>>2]);T(a,{name:c,fromWireType:h=>{for(var g=G[h>>2],p,m=h+4,q=0;q<=
g;++q){var n=h+4+q*b;if(q==g||0==l(n))m=d(m,n-m),void 0===p?p=m:(p+=String.fromCharCode(0),p+=m),m=n+b}W(h);return p},toWireType:(h,g)=>{if("string"!=typeof g)throw new R(`Cannot pass non-string to C++ string type ${c}`);var p=k(g),m=fb(4+p+b);G[m>>2]=p/b;e(g,m+4,p+b);null!==h&&h.push(W,m);return m},argPackAdvance:8,readValueFromPointer:Ba,A(h){W(h)}})},j:(a,b)=>{b=N(b);T(a,{D:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},n:(a,b,c)=>B.copyWithin(a,b,b+c),g:(a,b)=>{var c=P[a];
if(void 0===c)throw a=`${"_emval_take_value"} has unknown type ${Ta(a)}`,new R(a);a=c;a=a.readValueFromPointer(b);return Aa(a)},m:a=>{var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-z.buffer.byteLength+65535)/65536;try{z.grow(e);ia();var k=1;break a}catch(l){}k=void 0}if(k)return!0}return!1}},Y=function(){function a(c){Y=c.exports;z=Y.o;ia();Na=Y.t;ka.unshift(Y.p);
H--;f.monitorRunDependencies?.(H);0==H&&(null!==J&&(clearInterval(J),J=null),K&&(c=K,K=null,c()));return Y}var b={a:gb};H++;f.monitorRunDependencies?.(H);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){t(`Module.instantiateWasm callback failed with error: ${c}`),r(c)}L||=qa("zstd_codec.wasm")?"zstd_codec.wasm":f.locateFile?f.locateFile("zstd_codec.wasm",""):"zstd_codec.wasm";va(b,function(c){a(c.instance)}).catch(r);return{}}(),fb=a=>(fb=Y.q)(a),W=a=>(W=Y.r)(a),Sa=a=>(Sa=Y.s)(a),pa=
()=>(pa=Y.u)(),Z;K=function ib(){Z||jb();Z||(K=ib)};
function jb(){function a(){if(!Z&&(Z=!0,f.calledRun=!0,!ea)){ma=!0;M(ka);aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();la.unshift(b)}M(la)}}if(!(0<H)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)na();M(ja);0<H||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();jb();moduleRtn=ba;


  return moduleRtn;
}
);
})();
export default zstd_codec;
