
var zstd_codec = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,q,ba=new Promise((a,b)=>{aa=a;q=b}),ca=Object.assign({},f),r=f.printErr||console.error.bind(console);Object.assign(f,ca);ca=null;var t;f.wasmBinary&&(t=f.wasmBinary);var u,da=!1,x,z,A,B,D,E,ea,ha;function ia(){var a=u.buffer;f.HEAP8=x=new Int8Array(a);f.HEAP16=A=new Int16Array(a);f.HEAPU8=z=new Uint8Array(a);f.HEAPU16=B=new Uint16Array(a);f.HEAP32=D=new Int32Array(a);f.HEAPU32=E=new Uint32Array(a);f.HEAPF32=ea=new Float32Array(a);f.HEAPF64=ha=new Float64Array(a)}
var ja=[],ka=[],la=[],ma=!1;function na(){var a=f.preRun.shift();ja.unshift(a)}var F=0,H=null,I=null;function oa(a){f.onAbort?.(a);a="Aborted("+a+")";r(a);da=!0;a+=". Build with -sASSERTIONS for more info.";ma&&pa();a=new WebAssembly.RuntimeError(a);q(a);throw a;}var qa=a=>a.startsWith("data:application/octet-stream;base64,"),ra=a=>a.startsWith("file://"),J;function sa(a){if(a==J&&t)return new Uint8Array(t);throw"both async and sync fetching of the wasm failed";}
function ta(a){return t?Promise.resolve().then(()=>sa(a)):(void 0)(a).then(b=>new Uint8Array(b),()=>sa(a))}function ua(a,b,c){return ta(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{r(`failed to asynchronously prepare wasm: ${d}`);oa(d)})}
function va(a,b){var c=J;return t||"function"!=typeof WebAssembly.instantiateStreaming||qa(c)||ra(c)||"function"!=typeof fetch?ua(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){r(`wasm streaming compile failed: ${e}`);r("falling back to ArrayBuffer instantiation");return ua(c,a,b)}))}
var K=a=>{for(;0<a.length;)a.shift()(f)},wa,L=a=>{for(var b="";z[a];)b+=wa[z[a++]];return b},N={},O={},P={},Q,xa=a=>{throw new Q(a);},R,ya=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new R("Mismatched type converter count");for(var g=0;g<d.length;++g)S(d[g],k[g])}var d=[];d.forEach(function(k){P[k]=a});var e=Array(a.length),h=[],l=0;a.forEach((k,g)=>{O.hasOwnProperty(k)?e[g]=O[k]:(h.push(k),N.hasOwnProperty(k)||(N[k]=[]),N[k].push(()=>{e[g]=O[k];++l;l===h.length&&c(e)}))});0===h.length&&
c(e)};function za(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(O.hasOwnProperty(a)){if(c.H)return;throw new Q(`Cannot register type '${d}' twice`);}O[a]=b;delete P[a];N.hasOwnProperty(a)&&(b=N[a],delete N[a],b.forEach(e=>e()))}function S(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return za(a,b,c)}
var T=[],U=[],Aa=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=T.pop()||U.length;U[b]=a;U[b+1]=1;return b}};function V(a){return this.fromWireType(E[a>>2])}
var Ba={name:"emscripten::val",fromWireType:a=>{if(!a)throw new Q("Cannot use deleted val. handle = "+a);var b=U[a];9<a&&0===--U[a+1]&&(U[a]=void 0,T.push(a));return b},toWireType:(a,b)=>Aa(b),argPackAdvance:8,readValueFromPointer:V,F:null},Ca=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ea[c>>2])};case 8:return function(c){return this.fromWireType(ha[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Da=(a,b)=>Object.defineProperty(b,"name",{value:a}),
Ea=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Fa(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].F)return!0;return!1}function Ga(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Da(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var Ha=(a,b)=>{if(void 0===f[a].D){var c=f[a];f[a]=function(...d){if(!f[a].D.hasOwnProperty(d.length))throw new Q(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${f[a].D})!`);return f[a].D[d.length].apply(this,d)};f[a].D=[];f[a].D[c.G]=c}},Ia=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].D&&void 0!==f[a].D[c])throw new Q(`Cannot register public name '${a}' twice`);Ha(a,a);if(f.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].D[c]=b}else f[a]=b,void 0!==c&&(f[a].J=c)},Ja=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+4*d>>2]);return c},Ka,La=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,f["dynCall_"+a])(b,...c)):b=Ka.get(b)(...c);return b},Pa=(a,b)=>(...c)=>La(a,b,c),Qa=(a,b)=>{a=L(a);var c=a.includes("j")?Pa(a,b):Ka.get(b);if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c},Ra,Ta=a=>{a=Sa(a);var b=L(a);W(a);return b},Ua=(a,b)=>{function c(h){e[h]||O[h]||(P[h]?
P[h].forEach(c):(d.push(h),e[h]=!0))}var d=[],e={};b.forEach(c);throw new Ra(`${a}: `+d.map(Ta).join([", "]));},Va=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Wa=(a,b,c)=>{switch(b){case 1:return c?d=>x[d]:d=>z[d];case 2:return c?d=>A[d>>1]:d=>B[d>>1];case 4:return c?d=>D[d>>2]:d=>E[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Xa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Ya=(a,b)=>{var c=z,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-
a&&c.buffer&&Xa)return Xa.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var l=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|l:(e&7)<<18|h<<12|l<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Za="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,$a=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&B[c];)++c;
c<<=1;if(32<c-a&&Za)return Za.decode(z.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=A[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},ab=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)A[b>>1]=a.charCodeAt(e),b+=2;A[b>>1]=0;return b-d},bb=a=>2*a.length,cb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=D[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},
db=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var h=a.charCodeAt(e);if(55296<=h&&57343>=h){var l=a.charCodeAt(++e);h=65536+((h&1023)<<10)|l&1023}D[b>>2]=h;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},eb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},gb=a=>{a=a.getArg(X.C,0);return fb(a)};f.incrementExceptionRefcount=a=>{a=gb(a);hb(a)};f.decrementExceptionRefcount=a=>{a=gb(a);ib(a)};
f.getExceptionMessage=a=>{var b=gb(a);a=jb();var c=kb(4),d=kb(4);lb(b,c,d);b=E[c>>2];d=E[d>>2];c=b?Ya(b):"";W(b);if(d){var e=d?Ya(d):"";W(d)}mb(a);return[c,e]};for(var nb=Array(256),Y=0;256>Y;++Y)nb[Y]=String.fromCharCode(Y);wa=nb;Q=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};R=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};U.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>U.length/2-5-T.length;
Ra=f.UnboundTypeError=((a,b)=>{var c=Da(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var pb={l:()=>{oa("")},k:()=>{},i:(a,b,c,d)=>{b=L(b);S(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,h){return h?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(z[e])},F:null})},h:a=>S(a,Ba),e:(a,b,c)=>{b=L(b);S(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Ca(b,c),F:null})},d:(a,b,c,d,e,h,l)=>{var k=Ja(b,c);a=L(a);a=Va(a);e=Qa(d,e);Ia(a,function(){Ua(`Cannot call ${a} due to unbound types`,k)},b-1);ya(k,
g=>{var m=a;var n=a;g=[g[0],null].concat(g.slice(1));var w=e,p=g.length;if(2>p)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var C=null!==g[1]&&!1,M=Fa(g),Ma="void"!==g[0].name;w=[n,xa,w,h,Ea,g[0],g[1]];for(var v=0;v<p-2;++v)w.push(g[v+2]);if(!M)for(v=C?1:2;v<g.length;++v)null!==g[v].F&&w.push(g[v].F);M=Fa(g);v=g.length;var y="",G="";for(p=0;p<v-2;++p)y+=(0!==p?", ":"")+"arg"+p,G+=(0!==p?", ":"")+"arg"+p+"Wired";y=`\n        return function (${y}) {\n        if (arguments.length !== ${v-
2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${v-2}');\n        }`;M&&(y+="var destructors = [];\n");var Na=M?"destructors":"null",fa="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");C&&(y+="var thisWired = classParam['toWireType']("+Na+", this);\n");for(p=0;p<v-2;++p)y+="var arg"+p+"Wired = argType"+p+"['toWireType']("+Na+", arg"+p+");\n",fa.push("argType"+p);C&&(G="thisWired"+(0<G.length?
", ":"")+G);y+=(Ma||l?"var rv = ":"")+"invoker(fn"+(0<G.length?", ":"")+G+");\n";if(M)y+="runDestructors(destructors);\n";else for(p=C?1:2;p<g.length;++p)C=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==g[p].F&&(y+=`${C}_dtor(${C});\n`,fa.push(`${C}_dtor`));Ma&&(y+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [Oa,qb]=[fa,y+"}\n"];Oa.push(qb);g=Ga(Oa)(...w);n=Da(n,g);g=b-1;if(!f.hasOwnProperty(m))throw new R("Replacing nonexistent public symbol");void 0!==f[m].D&&void 0!==g?f[m].D[g]=
n:(f[m]=n,f[m].G=g);return[]})},b:(a,b,c,d,e)=>{b=L(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var h=32-8*c;e=k=>k<<h>>>h}var l=b.includes("unsigned")?function(k,g){return g>>>0}:function(k,g){return g};S(a,{name:b,fromWireType:e,toWireType:l,argPackAdvance:8,readValueFromPointer:Wa(b,c,0!==d),F:null})},a:(a,b,c)=>{function d(h){return new e(x.buffer,E[h+4>>2],E[h>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=L(c);S(a,{name:c,fromWireType:d,
argPackAdvance:8,readValueFromPointer:d},{H:!0})},f:(a,b)=>{b=L(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var e=E[d>>2],h=d+4;if(c)for(var l=h,k=0;k<=e;++k){var g=h+k;if(k==e||0==z[g]){l=l?Ya(l,g-l):"";if(void 0===m)var m=l;else m+=String.fromCharCode(0),m+=l;l=g+1}}else{m=Array(e);for(k=0;k<e;++k)m[k]=String.fromCharCode(z[h+k]);m=m.join("")}W(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var h,l="string"==typeof e;if(!(l||e instanceof
Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new Q("Cannot pass non-string to std::string");var k;if(c&&l)for(h=k=0;h<e.length;++h){var g=e.charCodeAt(h);127>=g?k++:2047>=g?k+=2:55296<=g&&57343>=g?(k+=4,++h):k+=3}else k=e.length;h=k;k=ob(4+h+1);g=k+4;E[k>>2]=h;if(c&&l){if(l=g,g=h+1,h=z,0<g){g=l+g-1;for(var m=0;m<e.length;++m){var n=e.charCodeAt(m);if(55296<=n&&57343>=n){var w=e.charCodeAt(++m);n=65536+((n&1023)<<10)|w&1023}if(127>=n){if(l>=g)break;h[l++]=n}else{if(2047>=
n){if(l+1>=g)break;h[l++]=192|n>>6}else{if(65535>=n){if(l+2>=g)break;h[l++]=224|n>>12}else{if(l+3>=g)break;h[l++]=240|n>>18;h[l++]=128|n>>12&63}h[l++]=128|n>>6&63}h[l++]=128|n&63}}h[l]=0}}else if(l)for(l=0;l<h;++l){m=e.charCodeAt(l);if(255<m)throw W(g),new Q("String has UTF-16 code units that do not fit in 8 bits");z[g+l]=m}else for(l=0;l<h;++l)z[g+l]=e[l];null!==d&&d.push(W,k);return k},argPackAdvance:8,readValueFromPointer:V,F(d){W(d)}})},c:(a,b,c)=>{c=L(c);if(2===b){var d=$a;var e=ab;var h=bb;
var l=k=>B[k>>1]}else 4===b&&(d=cb,e=db,h=eb,l=k=>E[k>>2]);S(a,{name:c,fromWireType:k=>{for(var g=E[k>>2],m,n=k+4,w=0;w<=g;++w){var p=k+4+w*b;if(w==g||0==l(p))n=d(n,p-n),void 0===m?m=n:(m+=String.fromCharCode(0),m+=n),n=p+b}W(k);return m},toWireType:(k,g)=>{if("string"!=typeof g)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var m=h(g),n=ob(4+m+b);E[n>>2]=m/b;e(g,n+4,m+b);null!==k&&k.push(W,n);return n},argPackAdvance:8,readValueFromPointer:V,F(k){W(k)}})},j:(a,b)=>{b=L(b);S(a,{I:!0,
name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},n:(a,b,c)=>z.copyWithin(a,b,b+c),g:(a,b)=>{var c=O[a];if(void 0===c)throw a=`${"_emval_take_value"} has unknown type ${Ta(a)}`,new Q(a);a=c;a=a.readValueFromPointer(b);return Aa(a)},m:a=>{var b=z.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-u.buffer.byteLength+65535)/65536;try{u.grow(e);ia();var h=
1;break a}catch(l){}h=void 0}if(h)return!0}return!1}},X=function(){function a(c){X=c.exports;u=X.o;ia();Ka=X.t;ka.unshift(X.p);F--;f.monitorRunDependencies?.(F);0==F&&(null!==H&&(clearInterval(H),H=null),I&&(c=I,I=null,c()));return X}var b={a:pb};F++;f.monitorRunDependencies?.(F);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){r(`Module.instantiateWasm callback failed with error: ${c}`),q(c)}J||=qa("zstd_codec.wasm")?"zstd_codec.wasm":f.locateFile?f.locateFile("zstd_codec.wasm",""):
"zstd_codec.wasm";va(b,function(c){a(c.instance)}).catch(q);return{}}(),ob=a=>(ob=X.q)(a),W=a=>(W=X.r)(a),Sa=a=>(Sa=X.s)(a),pa=()=>(pa=X.u)(),mb=a=>(mb=X.v)(a),kb=a=>(kb=X.w)(a),jb=()=>(jb=X.x)(),ib=a=>(ib=X.y)(a),hb=a=>(hb=X.z)(a),fb=a=>(fb=X.A)(a),lb=(a,b,c)=>(lb=X.B)(a,b,c),Z;I=function rb(){Z||sb();Z||(I=rb)};
function sb(){function a(){if(!Z&&(Z=!0,f.calledRun=!0,!da)){ma=!0;K(ka);aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();la.unshift(b)}K(la)}}if(!(0<F)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)na();K(ja);0<F||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();sb();moduleRtn=ba;


  return moduleRtn;
}
);
})();
export default zstd_codec;
